// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNzL8qJzwNWmKwZdqZ60kI62HGreKka5A',
    appId: '1:135569472897:web:f8906950a0db011f443c80',
    messagingSenderId: '135569472897',
    projectId: 'comicvault-78eb8',
    authDomain: 'comicvault-78eb8.firebaseapp.com',
    storageBucket: 'comicvault-78eb8.firebasestorage.app',
    measurementId: 'G-SYMTK5TWBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYY1tUdPQkN7zCI4uG27XXXfZds8lOv0k',
    appId: '1:135569472897:android:b1c40c05de668302443c80',
    messagingSenderId: '135569472897',
    projectId: 'comicvault-78eb8',
    storageBucket: 'comicvault-78eb8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT310TOTVydq8kzUAis1DZGV9hlR9qPfo',
    appId: '1:135569472897:ios:a7f9c84d14745972443c80',
    messagingSenderId: '135569472897',
    projectId: 'comicvault-78eb8',
    storageBucket: 'comicvault-78eb8.firebasestorage.app',
    iosBundleId: 'com.example.comicvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT310TOTVydq8kzUAis1DZGV9hlR9qPfo',
    appId: '1:135569472897:ios:a7f9c84d14745972443c80',
    messagingSenderId: '135569472897',
    projectId: 'comicvault-78eb8',
    storageBucket: 'comicvault-78eb8.firebasestorage.app',
    iosBundleId: 'com.example.comicvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNzL8qJzwNWmKwZdqZ60kI62HGreKka5A',
    appId: '1:135569472897:web:3f85d883d78b2d78443c80',
    messagingSenderId: '135569472897',
    projectId: 'comicvault-78eb8',
    authDomain: 'comicvault-78eb8.firebaseapp.com',
    storageBucket: 'comicvault-78eb8.firebasestorage.app',
    measurementId: 'G-GKW6VJ925D',
  );
}
